// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSQHPMrJnitYmX72DmQsnzGFrug6U65XA',
    appId: '1:28972307244:web:dd2c8f49e23d20c513d289',
    messagingSenderId: '28972307244',
    projectId: 'souqcom-7da1a',
    authDomain: 'souqcom-7da1a.firebaseapp.com',
    storageBucket: 'souqcom-7da1a.appspot.com',
    measurementId: 'G-BQ9Y2P39PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhdGyf6zev1nVfamVZ7Ejt62id3W4IOiI',
    appId: '1:28972307244:android:e10496f39a2e94ff13d289',
    messagingSenderId: '28972307244',
    projectId: 'souqcom-7da1a',
    storageBucket: 'souqcom-7da1a.appspot.com',
  );
}
